service:
  name: needs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless-admin

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http:
          method: get
          path: hello
