service:
  name: needs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http:
          method: get
          path: hello
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref DrobinkiApiGateway

resources:
  - ${file(resources/api-gateway.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/event-store.yml)}

