service:
  name: needs-typescript
# app and org for use with dashboard.serverless.com
app: needs-service
org: drobinki

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless-admin

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http:
          method: get
          path: hello
