---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template DynamoDB_Table: This template demonstrates
  the creation of a DynamoDB table.  **WARNING** This template creates an Amazon DynamoDB
  table. You will be billed for the AWS resources used if you create a stack from
  this template.'
Resources:
  DrobinkiCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: '*.drobinki.pl'
      ValidationMethod: DNS
  DNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: hosted zone for drobinki.pl
      Name: drobinki.pl
